post/post_models.py
user/user_models.py

1. User 모델 필드에 관리자 화면 등에서 표시되는 이름을 설정하는 옵션(verbose_name)을 추가했습니다.
2. Post 모델 정의 1차 구현했습니다.

[백엔드] User 모델 수정, Post 모델 정의

---

help/urls.py
post/post_models.py
templates/post/detail.html
templates/post/posts.html

1. 포스팅 메인 페이지와 글쓰기 페이지 HTML에서 location을 mountain_name으로 변경했습니다.
2. Post 모델에서 location을 mountain_name으로 변경했습니다.
3. help앱 urls.py에서 url 형식을 수정했습니다.

[백엔드] 수정: 포스팅 페이지 HTML 파일, Post모델, help앱 url 수정

---

config/urls.py
post/urls.py
templates/base.html
user/urls.py

1. 전체 프로젝트 url 적용 순서를 변경했습니다.
2. 메뉴바, 푸터의 url 연결을 템플릿 태그 형식으로 변경했습니다.
3. User, Post의 url에 static 경로를 적용했습니다.

[백엔드] 수정: url 관련 내용 수정 반영 요청

---

comment/admin.py
comment/apps.py
comment/comment_models.py
comment/comment_service.py
comment/tests.py
comment/urls.py
config/settings.py
config/urls.py
post/post_service.py
post/urls.py

1. settings파일에 comment 추가했습니다.
2. post url에서 comment 경로 삭제했습니다.
3. 전체 프로젝트 url에 comment url 추가했습니다.

[백엔드] Comment app 관련 설정 추가

---

templates/help/new.html
templates/help/review.html
templates/post/detail.html
user/static/css/base.css

content 태그 내 div 클래스 값 넣어주니 정상작동함.

post/detail.html 푸터 이상한 움직임 바로잡음.

---

user/user_models.py
user/user_service.py

로그인 시 유저의 위치 정보를 받을 필드를 모델에 추가하고, DB에 저장하는 기능을 추가했습니다.

[백엔드] 유저 위치 정보 필드 및 기능 추가

---

post/post_service.py

글 수정 및 삭제 함수에서 글 작성자를 확인하는 코드를 수정했습니다. (author -> user)

[백엔드] 글 수정 및 삭제 글쓴이 정보 확인 코드 수정

---

templates/post/detail.html

post/detail.html 삭제기능 구현완료.

---

post/post_models.py
post/post_service.py
templates/post/detail.html
user/user_models.py

1. Post, User 모델의 이미지 필드 옵션을 수정했습니다.
- 업로드 시 파일명을 커스텀해서 변환하는 함수를 적용시켰습니다.
2. 포스팅 삭제 시 삭제 처리되는 코드를 일부 수정했습니다.
3. 글 상세 페이지 접속 시 삭제 처리된 댓글은 보이지 않도록 처리했습니다.
4. User 모델에 유저 로그 모델 추가했습니다.

[백엔드] User, Post 모델 수정, 포스팅 삭제 및 댓글 표시 설정 수정

---

post/post_models.py
post/post_service.py
post/urls.py

1. 글 상세 페이지에서 좋아요 기능 데이터 전송 코드 작성했습니다.
2. 신고 기능 코드 작성했습니다.

[백엔드] 추가: 글 상세 페이지 좋아요, 신고 기능 코드 구현 1차

---

user/user_service.py

마이페이지 유저 게시글 및 좋아요 글 불러오기 추가했습니다.

[백엔드] 추가: 마이페이지 유저 게시글 및 좋아요 글 불러오기 추가

---

post/post_models.py

포스팅 시 s3에 업로드하는 이미지의 파일명이 커스텀되도록 코드를 수정했습니다.

[백엔드] 수정: 포스팅 업로드 이미지 파일명 설정 수정

---

post/post_models.py
user/user_service.py

마이페이지에서 삭제 처리된 글은 보이지 않도록 코드를 수정했습니다.

[백엔드] 수정: 마이페이지에서 삭제 처리된 글 안보이게 처리

---

templates/user/mypage.html

1. gitignore 내 한글 주석 영어로 수정했습니다.
2. settings 파일 내 aws 주석 해제, 불필요 주석 삭제했습니다.

[백엔드] 수정: gitignore, settings 파일 일부 내용 수정

---

comment/comment_service.py
comment/urls.py
post/post_service.py
post/static/js/posts.js
templates/post/detail.html

포스팅 내 댓글 작성을 비동기로 구현되도록 추가했습니다.

[백엔드] 기능 추가: 댓글 작성 기능 구현

---

mountain/views.py

활동로그 없을경우 추가

---

comment/comment_service.py
comment/urls.py
config/settings.py
post/static/js/posts.js
templates/post/detail.html

댓글 삭제 기능을 추가하면서 관련 파일의 내용을 일부 수정하고 코드를 추가했습니다.

[백엔드] 댓글 삭제 기능 관련 파일 수정 및 코드 추가

---

comment/comment_service.py
post/post_service.py
post/static/js/posts.js
templates/post/detail.html

1. 댓글 작성 및 삭제 시 비동기로 처리되도록 구현했습니다. 또, 삭제 시 안내 메시지가 뜨도록 처리했습니다.
2. 신고 작성 시 비동기로 처리되도록 구현했습니다. 또, 신고 접수 후 모달창이 닫히도록 처리했습니다.

[백엔드] 댓글, 신고 기능 수정

---

help/urls.py
help/views.py
templates/help/review.html

공지사항, 리뷰 글쓰기, 삭제 기능과 url을 수정했습니다.

수정-help 공지사항, 리뷰 글쓰기

---

config/settings.py
mountain/views.py
templates/user/signup.html
user/static/css/user/signup.css
user/static/js/user/signup.js
user/urls.py
user/user_service.py

1. 글 작성자와 해당 글을 보는 유저가 같을 때 댓글 입력창이 비활성화 되도록 구현했습니다.
2. 댓글 작성 후 바로 삭제 버튼의 기능이 활성화되지 않는 문제를 해결했습니다.
3. 글 작성자와 글을 보는 유저가 같을 때 좋아요 버튼 기능이 비활성화 되도록 구현했습니다.
4. 글 수정 시 기존 글을 가져오도록 관련 파일을 추가하고 코드를 일부 수정했습니다.

[백엔드] 수정 및 추가: 포스팅, 댓글, 좋아요 기능 일부 수정

---

post/admin.py
templates/post/detail.html
templates/post/new.html

1. post app의 admin 파일, 글 쓰기 페이지 html에서 불필요한 코드 삭제했습니다.
2. 글 상세 페이지 옆 테스트용 div 제거했습니다.

[백엔드] 수정 및 삭제: 불필요한 코드 및 요소 삭제 

---

post/static/css/posts.css
post/static/css/posts_all.css
templates/post/posts.html

전체 글 페이지와 상세 페이지의 CSS 파일을 분리해서 적용했습니다.

[프론트엔드] 수정 및 추가: 포스팅 전체, 상세 페이지 css 파일 분리

---

templates/post/posts.html

전체 글 페이지에서 프로필 사진 표시되도록 코드에 .url 추가했습니다.

[프론트엔드] 수정: 전체 글 페이지 프로필 사진 표시되게 수정

---

post/post_service.py
user/user_models.py

1. 유저 모델에 프로필 사진 필드의 default값을 설정했습니다.
2. post 기능 파일에 주석 설명을 추가했습니다.

[백엔드] 수정 및  추가: 유저 프로필 사진 default 값 설정, 주석 추가

---

post/post_service.py
post/static/css/posts.css
templates/post/new.html

글 쓰기 시 사진을 등록합니다. 다시 사진 등록 버튼을 누르고 취소를 누르고 폼을 제출하면 이미지가 없는 채로 작성되어 서버 에러가 발생합니다. 이 부분을 수정하고 에러 메시지를 추가했습니다. #108

[프론트엔드&백엔드] 수정 및 추가: 글 쓰기 사진 등록 오류 관련 코드 수정, 에러 메시지 추가

---

post/static/css/posts.css
templates/post/new.html

글 쓰기 폼 에러 메시지가 에러 발생했을 때 나타나도록 수정했습니다.

[프론트엔드] 수정: 글 쓰기 폼 에러 메시지 표시 수정

---

comment/comment_service.py
post/static/js/posts.js
templates/post/detail.html

댓글 작성 시 글 내용이 있을 때만 게시 버튼이 활성화되도록 관련 파일을 수정하고 코드를 추가했습니다.

[프론트엔드&백엔드] 수정 및 추가: 댓글 내용 있을 때만 게시 버튼 활성화로 수정

---

help/admin.py
mountain/admin.py
user/admin.py

관리자 페이지에서 각 모델을 관리할 수 있도록 모든 모델을 등록했습니다.

[백엔드] 수정 및 추가: 각 모델 클래스 관리자 페이지에 등록

---

comment/comment_models.py
help/models.py
mountain/models.py
user/user_models.py

관리자 페이지에서 각 모델이 표시되는 형식을 수정했습니다.

[백엔드] 수정: 각 모델이 관리자 페이지에서 표시되는 형식 수정

---

mountain/views.py

ai 서버에서 가져온 산의 id가 +1씩 되어 프론트엔드에 넘어갑니다!! 그래서 플러스하는 함수 적용하지 않고 가져온 그대로의 id로 프론트엔드에 넘어가도록 수정했습니다!

mountain_views.py 수정했습니다

---

mountain/views.py
templates/user/login.html
user/static/css/user/login.css

* [로그인] 화면에 게스트 링크 추가 하였습니다.
* [전체산], [산 상세] 페이지에 login_required 데코레이터를 제거 하였습니다.
* [산 상세] 비즈니스 로직에서 로그인 되지 않는 유저에 대해서 로그 수집하지 않도록 예외처리 하였습니다.
* mountains/views.py 불필요한 주석을 삭제하였습니다.

둘러보기 기능(비로그인) 구현 - 로그인, 전체산, 산상세

---

help/views.py
mountain/views.py
templates/base.html

전체산, 산상세페이지, 공지사항 접근할 수 있도록 해놨습니다. 그리고 로그아웃, 로그인  템플릿 표시 추가했습니다

수정 - 비회원일경우 기능 수정

---

help/views.py

1. 고객센터 전체 페이지를 비로그인 유저가 접근할 수 있도록 수정했습니다.
2. 공지사항 글쓰기, 수정, 삭제는 관리자만 가능하도록 백엔드 코드를 보충했습니다.
3. 리뷰 글쓰기, 수정, 삭제는 해당 유저나 관리자만 가능하도록 백엔드 코드를 보충했습니다.

둘러보기 기능(비로그인) 구현 - 고객센터

---

post/post_service.py
user/user_models.py

1. post앱에서의 views.py 올렸습니다(게시물에 들어갈때 게시물의 산의 아이디가 userviewlog에 저장됩니다)
2. userviewlog 모델 foreignkey에서 integer로 바꿨습니다.(안되는이유가 모델을 바꿔서 안되는것같습니다)

게시물 상세페이지 들어갈때 userviewlog에 기록 남기기

---

mountain/views.py
templates/base.html
user/static/js/base.js

- 게스트로 접속 시, 접속 불가한 메뉴로 접속 시도 시 로그인 유도와 접속 가능한 메뉴 안내 메시지를 보여줍니다.
- 게스트로 접속 시, 산 검색을 가능하게 하였습니다. (산 리스트 가져오기 API login_required 해제)
- 일감 번호: #167

[둘러보기] 안내 메시지 구현

---

templates/help/notice.html

다른관리자의 글 버튼 링크 삭제.

---

mountain/static/js/mountain/mountains_detail.js

a 태그에 관련 된 property(`target=_blank`)가 있어 쉽게 할 수 있었습니다.
- from 이슈: #177

[산상세] 맛집 클릭 시 새 탭or새 창에서 열리도록 수정

---

user/static/js/user/signup.js

- 가입한 유저들의 비밀번호의 보안을 위해서 영문 대/소문자, 숫자, 특수문자가 필수 포함사항이고 그 길이 또한 8~16으로 제한 두었습니다.
- `정규식`을 이용해서 구현했습니다.
- from issue: #181

[회원가입] 비밀번호 제약조건 추가

---

post/post_service.py
templates/post/new.html

업로드 직전 이미지를 webp 로 치환합니다~
1. redirect 대신 JsonResponse 를 사용하고, json 값을 사용해서 redirect 합니다
2. canvas 를 사용해서 이미지를 webp 로 치환합니다~
호진님 의견 주세효 ㅋ...

webp 로 치환해서 업로드

---

post/static/css/post_detail.css
post/static/css/posts.css
post/static/css/posts_all.css
post/static/js/posts.js
templates/base.html
templates/post/detail.html

포스팅 전체 페이지 및 헤더의 글쓰기 버튼에 마우스 올리면 포인터 모양으로 바뀌도록 변경했습니다.

[포스팅 페이지] 수정: 포스팅 페이지, 헤더 클릭 가능 요소 포인터 활성화

---

templates/post/new.html
templates/user/login.html
templates/user/signup.html
user/static/css/user/login.css
user/static/js/user/signup.js

로그인페이지- 로그인, 회원가입 수정
회원가입페이지- 취소, 가입하기 버튼 위치 변경

로그인 버튼 위치 수정, 회원가입 버튼 위치 수정
